### ISSUE TITLE
Can't get this working

### ISSUE THREAD

**Issue by mcnamee** [jonathantorres/medium-sdk-php#1]
Hi @jonathantorres 
Sorry if I'm overlooking something, however I can't get this working. I tried the examples:
- Got to authentication.php which presents a button I press
- That links to Medium which says 'We didn't understand your request'

I've also tried a real simple example with a self-issuing token:

```
<?php

  require_once __DIR__ . '/vendor/autoload.php';
  use JonathanTorres\MediumSdk\Medium;

  $medium = new Medium('TOKEN-I-GENERATED-FROM-SETTINGS');

  $user = $medium->getAuthenticatedUser();

  echo 'Authenticated user name is: ' . $user->name;
```

Which only outputs `Authenticated user name is:`

I also tried my self-issued token through Postman, which gave the correct results.

**Any suggestions?**

**Comment by jonathantorres** [comment]
If you created an application with a `client-id` and `client-secret` you must call the `authenticate()` method with the authorization code from the redirect callback. This is the recommended way for other users to interact with your application.

Take a closer look at the examples, on `callback.php` I grab the authentication code from the url.

``` php
    require('../vendor/autoload.php');

    use JonathanTorres\MediumSdk\Medium;

    $medium = new Medium([
        'client-id' => 'your-client-id',
        'client-secret' => 'your-client-secret',
        'redirect-url' => 'http://yourserver.com/callback.php',
        'state' => 'secret',
        'scopes' => 'basicProfile,publishPost,listPublications',
    ]);
    $medium->authenticate($_GET['code']);

    $authenticatedUser = $medium->getAuthenticatedUser();
```

Also, make sure that your `redirect-url` matches the same url you are using on your environment.

Hope this helps
