### ISSUE TITLE
userId was invalid

### ISSUE THREAD

**Issue by kafkiansky** [jonathantorres/medium-sdk-php#12]
Hi. Why i can not grab the publications from any user? 

<code>
$user = $medium->getAuthenticatedUser();
$publications = $medium->publications($user->data->id);
print_r($publications);
</code>

This code show nothing.

**Comment by jonathantorres** [comment]
Does it return an empty array or it returns nothing at all?

**Comment by kafkiansky** [comment]
Return that userId was Invalid. If I want to grab own publications, function return empty array.

**Comment by jonathantorres** [comment]
If it returns an empty array, most likely the user does not have any publications

**Comment by kafkiansky** [comment]
But publications exists. I also cannot grab own publications, but I really have them.

**Comment by jonathantorres** [comment]
Do you have a link to the publications?
