### ISSUE TITLE
cURL error 60: SSL certificate problem while using self issued token

### ISSUE THREAD

**Issue by 9itish** [jonathantorres/medium-sdk-php#3]
Hey Jonathan,

I am facing a problem with SSL certificates. I am using the following code with self-issued token supplied.

```
<?php

    require('vendor/autoload.php');
    use JonathanTorres\MediumSdk\Medium;

    $medium = new Medium('my-self issued token');
    $user = $medium->getAuthenticatedUser();

    echo 'Authenticated user name is: ' . $user->name;
```

I looked at the [another issue](https://github.com/jonathantorres/medium-sdk-php/issues/1) where the OP also used a self-issued token  but could still get the following output `Authenticated user name is:`. I don't get any output at all. 

I am using xampp to test locally. This is the error that I get:

```
Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\path\to\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187 
```

**Comment by 9itish** [comment]
I solved the issue by following the suggestions [here](https://laracasts.com/discuss/channels/general-discussion/curl-error-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate). 👍 

I would also like to point out that I had to use `$user->data->name;` instead of `$user->name;`. This may be a typing error so you can update it with the correct info [here](https://github.com/jonathantorres/medium-sdk-php#users). :)

**Comment by jonathantorres** [comment]
Thanks! Just updated the README.
