### ISSUE TITLE
Couldn't find a way to obtain refresh token.

### ISSUE THREAD

**Issue by minnur** [jonathantorres/medium-sdk-php#4]
Hi,

I think I found an issue. There is no way to get refresh token using your library. `Client::retrieveAccessToken(array $data)` method returns access_token only.

I had to modify the library in order to be able to get refresh token. When I have a chance I can work on a pull request.

Thanks

**Comment by jonathantorres** [comment]
Please do. Thanks!

**Comment by cazuba** [comment]
Hi @jonathantorres Can you give me access to send you a PR with the solution?

**Comment by jonathantorres** [comment]
Hello @cazuba, you don't need access. Just fork the repo and send a PR. More details here: https://help.github.com/articles/creating-a-pull-request/

Thanks!

**Comment by jonathantorres** [comment]
Added `getRefreshToken();` method on latest release.
